[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.97

[colors.primary]
background = '0x202020'
foreground = '0xddc7a1'

[colors.cursor]
text = '0x202020'
cursor = '0xddc7a1'

[colors.normal]
black = '0x2a2827'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xebdbb2'

[colors.bright]
black = '0x504945'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xfbf1c7'

[[colors.indexed_colors]]
index = 16
color = "0xe78a4e"

[[colors.indexed_colors]]
index = 17
color = "0xbd6f3e"

[[colors.indexed_colors]]
index = 18
color = "0x2a2827"

[[colors.indexed_colors]]
index = 19
color = "0x504945"

[[colors.indexed_colors]]
index = 20
color = "0xbdae93"

[[colors.indexed_colors]]
index = 21
color = "0xebdbb2"
