[colors.primary]
background = "#2E3440"  # nord0 – Polar Night
foreground = "#D8DEE9"  # nord4 – Snow Storm

[colors.normal]
black   = "#3B4252"  # nord1
red     = "#BF616A"  # nord11
green   = "#A3BE8C"  # nord14
yellow  = "#EBCB8B"  # nord13
blue    = "#81A1C1"  # nord9
magenta = "#B48EAD"  # nord15
cyan    = "#88C0D0"  # nord8
white   = "#E5E9F0"  # nord5

[colors.bright]
black   = "#4C566A"  # nord3
red     = "#BF616A"  # nord11
green   = "#A3BE8C"  # nord14
yellow  = "#EBCB8B"  # nord13
blue    = "#81A1C1"  # nord9
magenta = "#B48EAD"  # nord15
cyan    = "#8FBCBB"  # nord7
white   = "#ECEFF4"  # nord6

[colors.cursor]
text   = "#2E3440"  # can match background
cursor = "#D8DEE9"  # contrast foreground

[colors.selection]
text       = "#D8DEE9"
background = "#4C566A"
